name: Build ESP images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        target:
          - chip: esp32c6
            flash_freq: 80m
          - chip: esp32h2
            flash_freq: 48m

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3
          target: ${{ matrix.target.chip }}
          path: .
          command: |
            idf.py build && \
            esptool.py --chip ${{ matrix.target.chip }} merge_bin \
            -o build/co2_sensor_${{ matrix.target.chip }}.bin \
            --flash_mode dio \
            --flash_freq ${{ matrix.target.flash_freq }} \
            --flash_size 2MB \
            0x0 build/bootloader/bootloader.bin \
            0x10000 build/zigbee_co2_sensor.bin \
            0x8000 build/partition_table/partition-table.bin
      - run: |
          sudo mv build/zigbee_co2_sensor.elf build/co2_sensor_${{ matrix.target.chip }}.elf && \
          sudo mv build/zigbee_co2_sensor.map build/co2_sensor_${{ matrix.target.chip }}.map
      - name: Store built binaries
        uses: actions/upload-artifact@v4
        with:
          name: co2_sensor_${{ matrix.target.chip }}
          path: |
            build/co2_sensor_${{ matrix.target.chip }}.bin
            build/co2_sensor_${{ matrix.target.chip }}.elf
            build/co2_sensor_${{ matrix.target.chip }}.map
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - run: mkdir -p release && cp esp_web_tools_manifest.json release/
      - name: Fill in the release tag for the manifest file
        uses: richardrigutins/replace-in-files@v2
        with:
          files: release/esp_web_tools_manifest.json
          search-text: '{release}'
          replacement-text: ${{ github.ref_name }}
      - name: Download built binaries
        uses: actions/download-artifact@v4
        with:
          path: release
          pattern: co2_sensor_*
          merge-multiple: true
      - run: ls -R release && cat release/esp_web_tools_manifest.json
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
