name: Build ESP images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  create:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        target:
          - chip: esp32c6
            flash_freq: 80m
          - chip: esp32h2
            flash_freq: 48m

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3
          target: ${{ matrix.target.chip }}
          path: .
          command: |
            idf.py build &&
            idf.py merge-bin -o co2_sensor_${{ matrix.target.chip }}.bin -f raw
      - run: |
          sudo mv build/zigbee_co2_sensor.elf build/co2_sensor_${{ matrix.target.chip }}.elf && \
          sudo mv build/zigbee_co2_sensor.map build/co2_sensor_${{ matrix.target.chip }}.map
      - name: Store built binaries
        uses: actions/upload-artifact@v4
        with:
          name: co2_sensor_${{ matrix.target.chip }}
          path: |
            build/co2_sensor_${{ matrix.target.chip }}.bin
            build/co2_sensor_${{ matrix.target.chip }}.elf
            build/co2_sensor_${{ matrix.target.chip }}.map
  release:
    permissions:
      contents: write
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - run: mkdir -p release && cp esp_web_tools_manifest.json release/
      - name: Fill in the release tag for the manifest file
        uses: richardrigutins/replace-in-files@v2
        with:
          files: release/esp_web_tools_manifest.json
          search-text: '{release}'
          replacement-text: ${{ inputs.version }}
      - name: Download built binaries
        uses: actions/download-artifact@v4
        with:
          path: release
          pattern: co2_sensor_*
          merge-multiple: true
      - run: mkdir -p docs/bin_latest && cp release/co2_sensor_*.bin docs/bin_latest/
      - name: Commit binaries
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Release of ${{ inputs.version }}
          tagging_message: ${{ inputs.version }}
          skip_checkout: true
          skip_fetch: false
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
          tag_name: ${{ inputs.version }}
